# 全局配置
server:
  port: 8080

spring:
  # 注册到eureka的服务名称
  application:
    name: beidou-app
  cloud:
    # 服务提供方
    consul:
      discovery:
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 注册成功后的唯一标识
        instance-id: ${spring.application.name}
        # 注册成功后的服务名称
        service-name: ${spring.application.name}
      host: 127.0.0.1
      port: 8500
  # springboot集成jsp
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  # httpclient客户端配置
  httpclient:
    timeout:
      connect: 5000
      read: 5000
    connection:
      pool:
        maxTotal: 2000
        defaultMaxPerRoute: 2000
    retry:
      times: 0

# fegin启用http连接池支持
feign:
  httpclient:
    enabled: true
    # 最大连接数
    max-connections: 2000
    # 连接超时时间
    connection-timeout: 5000
# 设置fegin客户端的超时时间(默认超时为1s)
ribbon:
  ReadTimeout: 5000














